#!/usr/bin/env python

import os
import sys

# ellipses not included
truncate_at = int(sys.argv[1])
text        = str(sys.argv[2])

trailing_text = '...'

textlen = len(text)
for i in range(textlen):
    if i >= truncate_at:
        print(trailing_text)
        break;

    print(text[i], end='')
